version: '3.8'

services:
  notes:
    build:
      context: .
    image: mna200/paper:test
    ports:
      - 8000:8000
    environment:
      - SEVER_PORT=8000
      - AWS_ACCESS_KEY_ID=AKIAV2BJ4UJRQMBRGKDF
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-northeast-2
      - S3_BUCKET=hanghae-mini-project
      - S3_URL=https://hanghae-mini-project.s3.ap-northeast-2.amazonaws.com/
      - SEQUELIZE_NAME=root
      - SEQUELIZE_DATABASE=paper
      - SEQUELIZE_PASSWORD=ztas151615
      - SEQUELIZE_HOST=database-1.ctqwwyyctbbp.ap-northeast-2.rds.amazonaws.com database-1.ctqwwyyctbbp.ap-northeast-2.rds.amazonaws.com
      - SECRET_KEY=blog_Paper
      - ACCESS_TOKEN_KEY=Paper
      - REFRESH_TOKEN_KEY=Papers
      - NODEMAILER_USER=mna7805@gmail.com
      - NODEMAILER_PASS=ajnitrolelwhjkcz
      - NODEMAILER_HOST=smtp.gmail.com
      - NODEMAILER_PORT=587
      - NODEMAILER_SERVICE=gmail
      - KAKAO_REST_API=e5a559c65da6081afd5a18b2a2445eb8
      - NAVER_ID=stvp0AaZDQpJdE8hkVIu NAVER_SECRET=vkz9oS04zv
      - GOOGLE_ID=2097071383-f98pdnllgigjlj28i3kdcib44p0c3a2u.apps.googleusercontent.com
      - GOOGLE_SECRET=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
    volumes:
      - /app/node_modules
      - ./:/app
    command: nodemon --legacy-watch server.js
