version: '3.8'

services:
  notes:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - SEVER_PORT=8000
    volumes:
      - /app/node_modules
      - ./:/app
    command: nodemon --legacy-watch server.js
