version: '3.8'

services:
  notes:
    build:
      context: .
    image: mna200/paper:test
    ports:
      - 8000:8000
    environment:
      - SEVER_PORT=8000
    env_file:
      - /home/ubuntu/BE/.env
    volumes:
      - /app/node_modules
      - ./:/app
    command: |
      node server.js
