// 회원가입
###
POST http://13.124.124.215/user/signup
Content-Type: application/json

{
  "email": "test1235@naver.com",
  "nickname": "공백크5",
  "password" : "12345678",
  "confirmPassword" : "12345678"
}

// 회원탈퇴
###
PATCH http://127.0.0.1:8000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1Njg5ODM2MiwiZXhwIjoxNjU2OTA5MTYyfQ.MPBjcGbHuOuaNBrmpOWyacYSa0U7ybVxqDSu5ImpIKI
Content-Type: application/json

// 회원복구
###
PATCH http://127.0.0.1:8000/user/restore
Content-Type: application/json

{
  "email": "test1235@naver.com",
  "password" : "12345678"
}

// 로그인
###
POST http://127.0.0.1:8000/user/login
Content-Type: application/json

{
  "email": "test1235@naver.com",
  "password" : "12345678"
}

// 카카오 로그인
###
GET http://first-sw.shop/user/login/kakao/callback
Content-Type: application/json

// 네이버 로그인
###
GET http://13.124.124.215/user/login/naver/callback
Content-Type: application/json

// 구글 로그인
###
GET http://first-sw.shop/user/login/google/callback
Content-Type: application/json

// 이메일중복검사
###
POST http://13.124.124.215/user/idcheck/test1234@naver.com
Content-Type: application/json


// 닉네임중복검사
###
POST http://13.124.124.215/user/idcheck/공백크
Content-Type: application/json


// 마이프로필
###
GET  http://13.124.124.215/user/myprofile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIzLCJpYXQiOjE2NTY1ODc4ODd9.gZp1lb186g9MQwg6eoZPJN4bVJEnQ-QzwtC5_sGgOw8
Content-Type: application/json

// 마이프로필 수정
###
PATCH  http://13.124.124.215/user/myprofile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1NjU5MzgwNSwiZXhwIjoxNjU2NjA0NjA1fQ.ZkOJCBaXjc1tFic-6qzBaXb4HJit2OuoAuzwZXLPrDY
Content-Type: application/json

{
  "nickname": "공백크1",
  "introduction" : "기분나쁨"
}

// 이메일 인증
###
POST http://13.124.124.215/user/emailauth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1NjU5MjQwOCwiZXhwIjoxNjU2NjAzMjA4fQ.M4oh7-naCSR5CdUMdy-WdqGAefUj3rOII-yLXY3AO8c
Content-Type: application/json

{
  "email": "mna800@naver.com"
}

// 이메일 인증 체크
###
POST http://13.124.124.215/user/check-emailauth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1NjU5MjQwOCwiZXhwIjoxNjU2NjAzMjA4fQ.M4oh7-naCSR5CdUMdy-WdqGAefUj3rOII-yLXY3AO8c
Content-Type: application/json

{
  "emailAuth": "9635"
}

// 비밀번호 재설정 
###
PATCH http://13.124.124.215/user/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTY1NjU5MjQwOCwiZXhwIjoxNjU2NjAzMjA4fQ.M4oh7-naCSR5CdUMdy-WdqGAefUj3rOII-yLXY3AO8c
Content-Type: application/json

{
  "password": "123789"
}


// 리뷰 작성
###
post http://127.0.0.1:8000/api/review/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1Njc0OTc3NH0.RXuxbCKzzg3_069CBZlInTrTr891upF6yIdfii11ZEA
Content-Type: application/json

{
  "review": "아주 ",
  "rate": 5

}


// 리뷰 조회
###
GET  http://127.0.0.1:8000/api/review/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1Njc0NDg1Mn0.K7GJM8SL36MDeEC5s0vjtZYS7HYnBhP2uyFvB45kCXI
Content-Type: application/json

